### ISSUE TITLE
expand html5 semantic tag usage

### ISSUE THREAD

**Issue by rimmesbe** [saradyson/tea-cozy#4]
I like that you are using some semantic tags, but there are many more: `<main>, <section>, <article>` to name some. Html5 semantic tags are now a standard in the professional world so it's worth checking out.

https://www.pluralsight.com/guides/html-css/semantic-html?aid=701j0000001heIqAAI&promo=&oid=&utm_source=google&utm_medium=ppc&utm_campaign=CA_Dynamic&utm_content=&utm_term=&gclid=CjwKCAjwlrnNBRBMEiwApKU4PBiUM7wtxiyqNw-6Zoikh6ChlNul6tTL839Zj2h_JNTZcK6PE5WWlRoCiOYQAvD_BwE

**Comment by saradyson** [comment]
Thank you for the feedback! I will do that for the future.
