### ISSUE TITLE
SUMMARY

### ISSUE THREAD

**Issue by rimmesbe** [saradyson/tea-cozy#5]
Grade: exceeds expectations

Summary: Really nice job on this project, the site looks good. Your code was very organized and efficient. I created some issues with a few minor tweaks and suggestions, but overall I had very little to critique. Good job, you are ready for the next unit.

https://learn.shayhowe.com/advanced-html-css/semantics-accessibility/

**Comment by saradyson** [comment]
Hooray!  Thank you for the feedback, it is much appreciated. Ready to move forward. :)
